#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : natsort
Version  : 7.1.1
Release  : 301
URL      : https://files.pythonhosted.org/packages/06/73/132e1986f7d37826e39825097e09f2c86b1339609926210ebdaec74a3b72/natsort-7.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/06/73/132e1986f7d37826e39825097e09f2c86b1339609926210ebdaec74a3b72/natsort-7.1.1.tar.gz
Summary  : Simple yet flexible natural sorting in Python.
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: natsort-bin = %{version}-%{release}
Requires: natsort-python = %{version}-%{release}
Requires: natsort-python3 = %{version}-%{release}
Requires: PyICU
Requires: coverage
Requires: fastnumbers
Requires: hypothesis
Requires: pyparsing
Requires: six
Requires: sortedcontainers
Requires: zipp
BuildRequires : PyICU
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : fastnumbers
BuildRequires : hypothesis
BuildRequires : pep517
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyparsing
BuildRequires : pytest
BuildRequires : python-build
BuildRequires : six
BuildRequires : sortedcontainers
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zipp

%description
=======

%package bin
Summary: bin components for the natsort package.
Group: Binaries

%description bin
bin components for the natsort package.


%package python
Summary: python components for the natsort package.
Group: Default
Requires: natsort-python3 = %{version}-%{release}

%description python
python components for the natsort package.


%package python3
Summary: python3 components for the natsort package.
Group: Default
Requires: python3-core
Provides: pypi(natsort)

%description python3
python3 components for the natsort package.


%prep
%setup -q -n natsort-7.1.1
cd %{_builddir}/natsort-7.1.1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629265535
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
export MAKEFLAGS=%{?_smp_mflags}
if [ ! -f setup.py ]; then
printf "#!/usr/bin/env python\nfrom setuptools import setup\nsetup()" > setup.py
chmod +x setup.py
python3 setup.py build
else
python3 setup.py build
fi

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/natsort

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
