#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : natsort
Version  : 6.1.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/f9/d4/5a388273bfc1c2bed49fb68b2f8a2e159a88b56e0de9fa7ae45971697a14/natsort-6.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f9/d4/5a388273bfc1c2bed49fb68b2f8a2e159a88b56e0de9fa7ae45971697a14/natsort-6.1.0.tar.gz
Summary  : Natural Sorting utility
Group    : Development/Tools
License  : MIT
Requires: natsort-bin = %{version}-%{release}
Requires: natsort-license = %{version}-%{release}
Requires: natsort-python = %{version}-%{release}
Requires: natsort-python3 = %{version}-%{release}
Requires: PyICU
Requires: coverage
Requires: fastnumbers
Requires: hypothesis
Requires: pathlib
BuildRequires : PyICU
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : fastnumbers
BuildRequires : hypothesis
BuildRequires : pathlib
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
# Development Collateral
This file contains some files useful for development.
- `bump.sh` - Execute `bumpversion` then post-processes the CHANGELOG to handle corner-cases
that `bumpversion` cannot. Requires [`bump2version`](https://github.com/c4urself/bump2version),
which is the maintained fork of [`bumpversion`](https://github.com/peritus/bumpversion).
- `clean.sh` - This file cleans most files that are created during development.
Run in the project home directory.
- `requirements.txt` - Requirements to run tests.

%package bin
Summary: bin components for the natsort package.
Group: Binaries
Requires: natsort-license = %{version}-%{release}

%description bin
bin components for the natsort package.


%package license
Summary: license components for the natsort package.
Group: Default

%description license
license components for the natsort package.


%package python
Summary: python components for the natsort package.
Group: Default
Requires: natsort-python3 = %{version}-%{release}

%description python
python components for the natsort package.


%package python3
Summary: python3 components for the natsort package.
Group: Default
Requires: python3-core

%description python3
python3 components for the natsort package.


%prep
%setup -q -n natsort-6.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573425430
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/natsort
cp %{_builddir}/natsort-6.1.0/LICENSE %{buildroot}/usr/share/package-licenses/natsort/cbfbb32a50cfea3842805b831d828d639664c036
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/natsort

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/natsort/cbfbb32a50cfea3842805b831d828d639664c036

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
