#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : natsort
Version  : 6.0.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/b3/5d/c0fbee4ed688fe2ed6533dd4a0124e1470d6692bc29e1da06bc0861ed4ab/natsort-6.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b3/5d/c0fbee4ed688fe2ed6533dd4a0124e1470d6692bc29e1da06bc0861ed4ab/natsort-6.0.0.tar.gz
Summary  : Natural Sorting utility
Group    : Development/Tools
License  : MIT
Requires: natsort-bin = %{version}-%{release}
Requires: natsort-python = %{version}-%{release}
Requires: natsort-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
natsort
=======
.. image:: https://img.shields.io/pypi/v/natsort.svg
:target: https://pypi.org/project/natsort/

%package bin
Summary: bin components for the natsort package.
Group: Binaries

%description bin
bin components for the natsort package.


%package python
Summary: python components for the natsort package.
Group: Default
Requires: natsort-python3 = %{version}-%{release}

%description python
python components for the natsort package.


%package python3
Summary: python3 components for the natsort package.
Group: Default
Requires: python3-core

%description python3
python3 components for the natsort package.


%prep
%setup -q -n natsort-6.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556217142
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/natsort

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
